# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:37:23+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel, conint, constr


class DeliveryReceipt(BaseModel):
    api_key: Optional[str] = Field(
        None,
        alias='api-key',
        description='The API key that sent the SMS. This is useful when multiple accounts are sending webhooks to the same endpoint.',
        examples=['abcd1234'],
    )
    client_ref: Optional[str] = Field(
        None,
        alias='client-ref',
        description='If the `client-ref` is set when the SMS is sent, it will be included in the delivery receipt',
        examples=['my-personal-reference'],
    )
    err_code: Optional[str] = Field(
        None,
        alias='err-code',
        description='The status of the request. Will be a non `0` value if there has been an error, or if the status is unknown. See the [Delivery Receipt documentation](/messaging/sms/guides/delivery-receipts#dlr-error-codes) for more details',
        examples=['0'],
    )
    message_timestamp: Optional[str] = Field(
        None,
        alias='message-timestamp',
        description='The time when Vonage started to push this Delivery Receipt to your webhook endpoint.',
        examples=['2020-01-01 12:00:00'],
    )
    messageId: Optional[str] = Field(
        None,
        description='The Vonage ID for this message.',
        examples=['0A0000001234567B'],
    )
    msisdn: Optional[str] = Field(
        None,
        description='The number the message was sent to. Numbers are specified in E.164 format.',
        examples=['447700900000'],
    )
    network_code: Optional[str] = Field(
        None,
        alias='network-code',
        description='The Mobile Country Code Mobile Network Code (MCCMNC) of the carrier this phone number is registered with.',
        examples=['12345'],
    )
    nonce: Optional[str] = Field(
        None,
        description='A random string to be used when calculating the signature. _Only included if you have signatures enabled_',
        examples=['ec11dd3e-1e7f-4db5-9467-82b02cd223b9'],
    )
    price: Optional[str] = Field(
        None, description='The cost of the message', examples=['0.03330000']
    )
    scts: Optional[str] = Field(
        None,
        description='When the DLR was received from the carrier in the following format `YYMMDDHHMM`. For example, `2001011400` is at `2020-01-01 14:00`',
        examples=['2001011400'],
    )
    sig: Optional[str] = Field(
        None,
        description='The signature to enable verification of the source of this webhook. Please see the [developer documentation for validating signatures](/concepts/guides/signing-messages) for more information, or use one of our published SDKs. _Only included if you have signatures enabled_',
        examples=['1A20E4E2069B609FDA6CECA9DE18D5CAFE99720DDB628BD6BE8B19942A336E1C'],
    )
    status: Optional[str] = Field(
        None,
        description='A code that explains where the message is in the delivery process.',
        examples=['delivered'],
    )
    timestamp: Optional[str] = Field(
        None,
        description='A timestamp in Unix (seconds since the epoch) format. _Only included if you have signatures enabled_',
        examples=['1582650446'],
    )
    to: Optional[str] = Field(
        None,
        description='The SenderID you set in `from` in your request.',
        examples=['AcmeInc'],
    )


class ErrorMessage(BaseModel):
    error_text: Optional[str] = Field(
        None,
        alias='error-text',
        description='The description of the error',
        examples=['Missing to param'],
    )
    status: Optional[str] = Field(
        None, description='The error status of the message', examples=['2']
    )


class ErrorXml(BaseModel):
    messages: Optional[List[ErrorMessage]] = None


class InboundMessage(BaseModel):
    api_key: str = Field(
        ...,
        alias='api-key',
        description='The Vonage API Key of the receiving account.',
        examples=['abcd1234'],
    )
    concat: Optional[str] = Field(
        None,
        description='True - if this is a concatenated message. This field does not exist if it is a single message',
        examples=['true'],
    )
    concat_part: Optional[str] = Field(
        None,
        alias='concat-part',
        description='The number of this part in the message. Counting starts at 1.',
        examples=['2'],
    )
    concat_ref: Optional[str] = Field(
        None,
        alias='concat-ref',
        description='The transaction reference. All parts of this message share this value.',
        examples=['1'],
    )
    concat_total: Optional[str] = Field(
        None,
        alias='concat-total',
        description='The number of parts in this concatenated message.',
        examples=['3'],
    )
    data: Optional[bytes] = Field(
        None, description='The content of this message, if type is binary.'
    )
    keyword: str = Field(
        ...,
        description='The first word in the message body. Converted to upper case.',
        examples=['HELLO'],
    )
    message_timestamp: str = Field(
        ...,
        alias='message-timestamp',
        description='The time when Vonage started to push this Delivery Receipt to your webhook endpoint.',
        examples=['2020-01-01 12:00:00'],
    )
    messageId: str = Field(
        ..., description='The ID of the message', examples=['0A0000000123ABCD1']
    )
    msisdn: str = Field(
        ...,
        description='The phone number that this inbound message was sent from. Numbers are specified in E.164 format.',
        examples=['447700900001'],
    )
    nonce: Optional[str] = Field(
        None,
        description='A random string that forms part of the signed set of parameters, it adds an extra element of unpredictability into the signature for the request. You use the nonce and timestamp parameters with your shared secret to calculate and validate the signature for inbound messages.',
        examples=['aaaaaaaa-bbbb-cccc-dddd-0123456789ab'],
    )
    text: str = Field(
        ...,
        description='The message body for this inbound message.',
        examples=['Hello world'],
    )
    timestamp: Optional[str] = Field(
        None,
        description='A unix timestamp representation of message-timestamp.',
        examples=['1578787200'],
    )
    to: str = Field(
        ...,
        description='The phone number the message was sent to. **This is your virtual number**. Numbers are specified in E.164 format.',
        examples=['447700900000'],
    )
    type: str = Field(
        ...,
        description='Possible values are:\n\n  - `text` - standard text.\n  - `unicode` - URLencoded   unicode  . This is valid for standard GSM, Arabic, Chinese, double-encoded characters and so on.\n  - `binary` - a binary message.\n',
        examples=['text'],
    )
    udh: Optional[str] = Field(
        None, description='The hex encoded User Data Header, if type is binary'
    )


class Message(BaseModel):
    account_ref: Optional[str] = Field(
        None,
        alias='account-ref',
        description='**Advanced**: An optional string used to identify separate accounts using the SMS endpoint for billing purposes. To use this feature, please email [support@nexmo.com](mailto:support@nexmo.com)',
        examples=['customer1234'],
    )
    client_ref: Optional[str] = Field(
        None,
        alias='client-ref',
        description='If a `client-ref` was included when sending the SMS, this field will be included and hold the value that was sent.',
        examples=['my-personal-reference'],
    )
    message_id: Optional[str] = Field(
        None,
        alias='message-id',
        description='The ID of the message',
        examples=['0A0000000123ABCD1'],
    )
    message_price: Optional[str] = Field(
        None,
        alias='message-price',
        description='The estimated cost of the message',
        examples=['0.03330000'],
    )
    network: Optional[str] = Field(
        None,
        description='The estimated ID of the network of the recipient',
        examples=['12345'],
    )
    remaining_balance: Optional[str] = Field(
        None,
        alias='remaining-balance',
        description='Your estimated remaining balance',
        examples=['3.14159265'],
    )
    status: Optional[str] = Field(
        None,
        description='The status of the message. See [Troubleshooting Failed SMS](/messaging/sms/guides/troubleshooting-sms).',
        examples=['0'],
    )
    to: Optional[str] = Field(
        None,
        description='The number the message was sent to. Numbers are specified in E.164 format.',
        examples=['447700900000'],
    )


class MessageClass(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class Type(Enum):
    text = 'text'
    binary = 'binary'
    unicode = 'unicode'


class NewMessage(BaseModel):
    account_ref: Optional[str] = Field(
        None,
        alias='account-ref',
        description='**Advanced**: An optional string used to identify separate accounts using the SMS endpoint for billing purposes. To use this feature, please email [support@nexmo.com](mailto:support@nexmo.com)',
        examples=['customer1234'],
    )
    api_key: constr(min_length=8, max_length=8) = Field(
        ..., description='Your API key', examples=['abcd1234']
    )
    api_secret: Optional[constr(min_length=6, max_length=32)] = Field(
        None,
        description='Your API secret. Required unless `sig` is provided',
        examples=['abcdef0123456789'],
    )
    body: Optional[str] = Field(
        None,
        description='**Advanced**: Hex encoded binary data. Depends on `type` parameter having the value `binary`.',
        examples=['0011223344556677'],
    )
    callback: Optional[str] = Field(
        None,
        description='**Advanced**: The webhook endpoint the delivery receipt for this sms is sent to. This parameter overrides the webhook endpoint you set in Dashboard. Max 100 characters.',
        examples=['https://example.com/sms-dlr'],
    )
    client_ref: Optional[str] = Field(
        None,
        alias='client-ref',
        description='**Advanced**: You can optionally include your own reference of up to 100 characters.',
        examples=['my-personal-reference'],
    )
    content_id: Optional[str] = Field(
        None,
        alias='content-id',
        description='**Advanced**: A string parameter that satisfies regulatory requirements when sending an SMS to specific countries. For more information please refer to the [Country-Specific Outbound SMS Features](https://help.nexmo.com/hc/en-us/articles/115011781468)',
        examples=['1107457532145798767'],
    )
    entity_id: Optional[str] = Field(
        None,
        alias='entity-id',
        description='**Advanced**: A string parameter that satisfies regulatory requirements when sending an SMS to specific countries. For more information please refer to the [Country-Specific Outbound SMS Features](https://help.nexmo.com/hc/en-us/articles/115011781468)',
        examples=['1101456324675322134'],
    )
    from_: str = Field(
        ...,
        alias='from',
        description="The name or number the message should be sent from. Alphanumeric senderID's are not supported in all countries, see [Global Messaging](/messaging/sms/guides/global-messaging#country-specific-features) for more details. If alphanumeric, spaces will be ignored. Numbers are specified in E.164 format.",
        examples=['AcmeInc'],
    )
    message_class: Optional[MessageClass] = Field(
        None,
        alias='message-class',
        description='**Advanced**: The Data Coding Scheme value of the message',
    )
    protocol_id: Optional[int] = Field(
        None,
        alias='protocol-id',
        description='**Advanced**: The value of the [protocol identifier](https://en.wikipedia.org/wiki/GSM_03.40#Protocol_Identifier) to use. Ensure that the value is aligned with `udh`.',
        examples=[127],
    )
    sig: Optional[constr(min_length=16, max_length=60)] = Field(
        None,
        description='The hash of the request parameters in alphabetical order, a timestamp and the signature secret. See [Signing Requests](/concepts/guides/signing-messages) for more details.',
    )
    status_report_req: Optional[bool] = Field(
        True,
        alias='status-report-req',
        description='**Advanced**: Boolean indicating if you like to receive a [Delivery Receipt](/messaging/sms/building-blocks/receive-a-delivery-receipt).',
        examples=[False],
    )
    text: Optional[str] = Field(
        None,
        description='The body of the message being sent. If your message contains characters that can be encoded according to the GSM Standard and Extended tables then you can set the `type` to `text`. If your message contains characters outside this range, then you will need to set the `type` to `unicode`.',
        examples=['Hello World!'],
    )
    to: constr(pattern=r'\d{7,15}', min_length=7, max_length=15) = Field(
        ...,
        description='The number that the message should be sent to. Numbers are specified in E.164 format.',
        examples=['447700900000'],
    )
    ttl: Optional[conint(ge=20000, le=604800000)] = Field(
        259200000,
        description='**Advanced**: The duration in milliseconds the delivery of an SMS will be attempted.§§ By default Vonage attempts delivery for 72 hours, however the maximum effective value depends on the operator and is typically 24 - 48 hours. We recommend this value should be kept at its default or at least 30 minutes.',
        examples=[900000],
    )
    type: Optional[Type] = Field(
        'text',
        description='**Advanced**: The format of the message body',
        examples=['text'],
    )
    udh: Optional[str] = Field(
        None,
        description='**Advanced**: Your custom Hex encoded [User Data Header](https://en.wikipedia.org/wiki/User_Data_Header). Depends on `type` parameter having the value `binary`.',
        examples=['06050415811581'],
    )


class SMS(BaseModel):
    message_count: Optional[str] = Field(
        None,
        alias='message-count',
        description='The amount of messages in the request',
        examples=['1'],
    )
    messages: Optional[List[Message]] = None


class Messages(BaseModel):
    count: Optional[int] = Field(None, examples=[1])


class SMSXml(BaseModel):
    messages: Optional[Union[List[Message], Messages]] = None


class FieldFormatPostResponse1(RootModel[Union[SMSXml, ErrorXml]]):
    root: Union[SMSXml, ErrorXml]


class Format(Enum):
    json = 'json'
    xml = 'xml'


class Error(BaseModel):
    message_count: Optional[str] = Field(
        None,
        alias='message-count',
        description='The amount of messages in the request',
        examples=['1'],
    )
    messages: Optional[List[ErrorMessage]] = None


class FieldFormatPostResponse(RootModel[Union[SMS, Error]]):
    root: Union[SMS, Error]
